Added query map loader to pg client
aria-afk/go-get-tickets pull request #3
Opened 2024-12-12 22:05 UTC by aria-afk

We can now load .sql query files into a query map. We can always write inline strings too but I do like having the organization and ability to test locally a bit more.

2024-12-12 22:06 UTC, aria-afk commented on pg/pg.go
> +func pop(arr *[]string) string {
could move this to utils and make it take any type i guess since go doesn't have a native `pop`

2025-05-25 02:07 UTC, cjdesno requested changes
Let's talk about the string lookup thing a little more first

2025-05-25 02:07 UTC, cjdesno commented on pg/pg_test.go
> +		if one != "SELECT 1 + $1;" {
If we are using writefile for these instead of having a test_data dir, we might as well take advantage of that by capturing the values as string constants instead of copypasting.

2025-05-25 02:07 UTC, cjdesno commented on pg/pg.go
> +		QueryMap: make(map[string]string, 0),
I feel a little weird about runtime-accessing queries via string key map. I feel like this necessitates a lot of extra key-presence checks

2025-05-25 21:46 UTC, closed without merging